# Plugin Manager
# ========================================
[[plugins]]
repo = 'Shougo/dein.vim'

# Proc
# ========================================
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# Colorsheme
# ========================================
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'KKPMW/moonshine-vim'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

# Util
# ========================================
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'yuratomo/w3m.vim'
hook_add = '''
    let g:w3m#history#save_file = expand('~/.w3m/.vim_w3m_hist')
'''

[[plugins]]
repo = 'thinca/vim-ref.git'
hook_add = '''
    let g:ref_source_webdict_sites = {
    \   'je':{
    \       'url': 'http://dictionary.infoseek.ne.jp/jeword/%s',
    \   },
    \   'ej':{
    \       'url': 'http://dictionary.infoseek.ne.jp/ejword/%s',
    \   },
    \   'wiki':{
    \       'url': 'http://ja.wikipedia.org/wiki/%s',
    \   },
    \ }
    let g:ref_source_webdict_sites.default = 'ej'
'''

[[plugins]]
repo = 'jacquesbh/vim-showmarks'
hook_add = '''
    nmap <silent> ms :DoShowMarks<CR>
    nmap <silent> md :NoShowMarks<CR>
'''
         
[[plugins]]
repo = 'junegunn/goyo.vim'

# Edit
# ========================================
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'rhysd/vim-operator-surround'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
    nmap p <Plug>(yankround-p)
    nmap P <Plug>(yankround-P)
    nmap gp <Plug>(yankround-gp)
    nmap gP <Plug>(yankround-prev)
    nmap <C-p> <Plug>(yankround-prev)
    nmap <C-n> <Plug>(yankround-next)
'''

# Markdown
# ========================================
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

# Git
# ========================================
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
    let g:gitgutter_sign_added = '・'
    let g:gitgutter_sign_modified = '・'
    let g:gitgutter_sign_removed = '・'
    let g:gitgutter_sign_removed_first_line = '・'
    let g:gitgutter_sign_modified_removed = '・' 
'''

# Go
# ========================================
[[plugins]]
repo = 'fatih/vim-go'
