# Deverope
# ========================================
[[plugins]]
repo = 'andviro/flake8-vim'
on_ft = 'python'

#[[plugins]]
#repo = 'zchee/deoplete-jedi'
#depends = ['deoplete.nvim']
#on_ft = 'python'
#hook_post_update = '''
#    let g:dein#plugin.build = "pip install jedi"
#'''
#hook_add = '''
#    let g:deoplete#sources#jedi#python_path = '/usr/bin/python3.7'
#'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_post_update = '''
    let g:dein#plugin.build = "pip install jedi"
'''
hook_add = '''
    autocmd FileType python setlocal omnifunc=jedi#completions
    let g:jedi#auto_vim_configuration = 0
    let g:jedi#popup_select_first = 0
    let g:jedi#rename_command = '<Leader>R'
    if !exists('g:neocomplete#force_omni_input_patterns')
        let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'
'''    

[[plugins]]
repo = 'scrooloose/syntastic'
on_if = 1
hook_post_update = '''
    let g:dein#plugin.build = "pip install flake8"
    let g:dein#plugin.build = "npm -g install coffeelint" 
'''
hook_post_source = '''
    let g:syntastic_python_checkers = ["flake8"]
'''

[[plugins]]
repo = 'Shougo/neocomplete'
on_if = 1
#[[plugins]]
#repo = 'Shougo/deoplete.nvim'
#on_if = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_if = 1
hook_add = '''
    let g:quickrun_config = {
        \ "_": {"runner": "vimproc"},
        \ }
'''
    
[[plugins]]
repo = 'Shougo/vimshell.vim'
on_if = 1

# Unite
# ========================================
[[plugins]]
repo = 'Shougo/unite.vim'
hook_post_source = '''
    "start unite in insert mode
    let g:unite_enable_start_insert = 1
    "use vimfiler to open directory
    call unite#custom_default_action("source/bookmark/directory", "vimfiler")
    call unite#custom_default_action("directory", "vimfiler")
    call unite#custom_default_action("directory_mru", "vimfiler")
    autocmd MyAutoCmd FileType unite call s:unite_settings()
    function! s:unite_settings()
        imap <buffer> <ESC><ESC> <Plug>(unite_exit)
        imap <buffer> <ESC> <Plug>(unite_exit)
        imap <buffer> <C-n> <Plug>(unite_select_next_line)
        imap <buffer> <C-p> <Plug>(unite_select_previous_line)
    endfunction
'''

[[plugins]]
repo = 'h1mesuke/unite-outline'
on_source = ['unite.vim']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = "Shougo/vimfiler"
hook_post_source = '''
    let g:vimfiler_as_default_explorer = 1
    let g:vimfiler_enable_auto_cd = 1
    let g:vimfiler_ignore_pattern = "\%(^\..*\|\.pyc$\)"

    autocmd MyAutoCmd FileType vimfiler call s:vimfiler_settings()
    function! s:vimfiler_settings()
        nmap <buffer> ^^ <Plug>(vimfiler_switch_to_parent_directory)
        nmap <buffer> R <Plug>(vimfiler_redraw_screen)
        nmap <buffer> <C-l> <C-w>l
    endfunction
'''
