#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap &
fi

if [ -f "$userresources" ]; then
    xrdb -merge $userresources
fi

if [ -f "$usermodmap" ]; then
    xmodmap $usermodmap &
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# set IM 
export DefaultImModule=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
fcitx &

# set cursor image
xsetroot -cursor_name left_ptr 

# set Japanese Keyboad Layout
# setxkbmap -layout jp

# set disable middle button
xinput set-button-map 15 1 0 3 4 5 6 7

# disable beep
xset b off

# typematic delay rate
xset r rate 190 60

# start urxvt deamon
urxvtd --quiet --fork --opendisplay &

# start xmonad
exec xmonad
